// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_LY_3Otpu2Y_4tuOzdZGv3VpsxJXuo4',
    appId: '1:589010851164:web:674e1d95776fea7e035d99',
    messagingSenderId: '589010851164',
    projectId: 'fitnessapp-22070',
    authDomain: 'fitnessapp-22070.firebaseapp.com',
    storageBucket: 'fitnessapp-22070.appspot.com',
    measurementId: 'G-YMZJD87RYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8WsL3WNu6xV8hBdXyD8SErBDoHH8j6c',
    appId: '1:589010851164:android:41f6062337f2853a035d99',
    messagingSenderId: '589010851164',
    projectId: 'fitnessapp-22070',
    storageBucket: 'fitnessapp-22070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJE-8cc0WyjohcoE2cN0Q8y1yTXoTj3Q',
    appId: '1:589010851164:ios:0121cae700b8e03b035d99',
    messagingSenderId: '589010851164',
    projectId: 'fitnessapp-22070',
    storageBucket: 'fitnessapp-22070.appspot.com',
    iosClientId: '589010851164-se86bslbaal4aclgpm5sfhruo2cu7gfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJE-8cc0WyjohcoE2cN0Q8y1yTXoTj3Q',
    appId: '1:589010851164:ios:0121cae700b8e03b035d99',
    messagingSenderId: '589010851164',
    projectId: 'fitnessapp-22070',
    storageBucket: 'fitnessapp-22070.appspot.com',
    iosClientId: '589010851164-se86bslbaal4aclgpm5sfhruo2cu7gfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnesshub',
  );
}
